#!/usr/bin/env bash
#see LICENSE for license

cd ../riscv-tools/riscv-isa-sim && ln -s ../../rocc-template/isa-sim/sha3 sha3
rm configure.ac && ln -s ../../rocc-template/isa-sim/configure.ac
cd ../../src/main/scala && ln -s ../../../rocc-template/config/PrivateConfigs.scala PrivateConfigs.scala
